# Generated by Django 5.1.1 on 2024-10-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorretoraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('url_base', models.URLField()),
                ('exige_passphrase', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures'), ('margin', 'Margin')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CorretoraUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('passphrase', models.CharField(blank=True, max_length=255, null=True)),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora.corretoraconfig')),
            ],
        ),
    ]
