# Generated by Django 5.1.1 on 2024-10-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretoraconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_corretoras/'),
        ),
    ]
