# Generated by Django 5.1.1 on 2024-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0003_corretora_delete_bybitcorretora'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretora',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='corretora_logos/'),
        ),
    ]
