# Generated by Django 5.1.1 on 2024-09-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=10, unique=True)),
                ('cor', models.CharField(default='#FF5733', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_moedas/')),
            ],
        ),
    ]
