# Generated by Django 5.1.1 on 2024-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocotacao',
            name='preco',
        ),
        migrations.AddField(
            model_name='historicocotacao',
            name='abertura',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicocotacao',
            name='alta',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicocotacao',
            name='baixa',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicocotacao',
            name='fechamento',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='historicocotacao',
            name='volume',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
