# Generated by Django 5.1.1 on 2024-09-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('preco', models.DecimalField(decimal_places=10, max_digits=20)),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moeda.moeda')),
            ],
            options={
                'unique_together': {('moeda', 'data')},
            },
        ),
    ]
