# Generated by Django 5.1.1 on 2024-09-16 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0003_historicocotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocotacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
