# Generated by Django 5.1.1 on 2024-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeda', '0004_alter_historicocotacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocotacao',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
