# Generated by Django 5.1.1 on 2024-09-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('moeda', '0005_alter_historicocotacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='moeda',
            name='corretora_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='moeda',
            name='corretora_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
