# Generated by Django 5.1.1 on 2024-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='quantidade',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
