# Generated by Django 5.1.1 on 2024-10-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativo', '0001_initial'),
        ('moeda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='moeda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moeda.moeda'),
        ),
    ]
